---
- name: Configure OSPF and Static Routes on FortiGate
  hosts: fortigates
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios

  vars:
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
    vdom: "root"
    fortigate_token: "6f9bb755jrjhjnywr8mqf9Nj0ghsn7"

  tasks:
    - name: Configure OSPF
      fortios_router_ospf:
        vdom: "{{ vdom }}"
        state: "present"
        router_ospf:
          router_id: "10.63.252.3"
          area:
            - id: "0.0.0.0"
          ospf_interface:
            - interface: "vpn_branch"
              network_type: "point-to-point"
              name: "vpn_0"
            - interface: "vpn_mfn"
              network_type: "point-to-point"
              name: "vpn_1"
          network:
            - prefix: "10.18.1.0 255.255.255.0"
            - prefix: "10.63.252.0 255.255.255.0"
          redistribute:
            - type: "connected"
              status: "enable"
            - type: "static"
              status: "enable"
            - type: "rip"
              status: "disable"
            - type: "bgp"
              status: "disable"
            - type: "isis"
              status: "disable"
        access_token: "{{ fortigate_token }}"

    - name: Configure Static Route
      fortios_router_static:
        vdom: "{{ vdom }}"
        state: "present"
        router_static:
          dst: "10.195.199.0 255.255.255.0"
          distance: 1
          sdwan_zone: "sd_wan_isp"
        access_token: "{{ fortigate_token }}"
